services:
  django:
    container_name: django-mbooks
    build:
      context: ./books
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./books:/usr/src/app/
    ports:
      - 8089:8000
    env_file:
      - .env

