# Generated by Django 5.1 on 2024-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('pages', models.PositiveIntegerField()),
                ('published_date', models.DateField()),
                ('book_link', models.URLField(blank=True, null=True)),
                ('book_cover_link', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
